# Generated by Django 6.0.3 on 2026-04-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('pts_last_5', models.IntegerField(default=0)),
                ('avg_gf', models.FloatField(default=0.0)),
                ('avg_ga', models.FloatField(default=0.0)),
                ('avg_sot', models.FloatField(default=0.0)),
                ('goal_diff', models.FloatField(default=0.0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.league')),
            ],
            options={
                'unique_together': {('league', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('ftr', models.CharField(max_length=1)),
                ('home_elo', models.FloatField()),
                ('away_elo', models.FloatField()),
                ('home_pts_last_5', models.IntegerField()),
                ('away_pts_last_5', models.IntegerField()),
                ('home_avg_gf', models.FloatField()),
                ('home_avg_ga', models.FloatField()),
                ('away_avg_gf', models.FloatField()),
                ('away_avg_ga', models.FloatField()),
                ('home_avg_sot', models.FloatField()),
                ('away_avg_sot', models.FloatField()),
                ('h2h_home_win_rate', models.FloatField()),
                ('home_goal_diff', models.FloatField()),
                ('away_goal_diff', models.FloatField()),
                ('elo_diff', models.FloatField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team')),
            ],
        ),
    ]
