# Generated by Django 6.0.3 on 2026-04-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matchrecord_btts_no_prob_matchrecord_btts_prediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrecord',
            name='btts_no_prob',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='btts_prediction',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='btts_yes_prob',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='dnb_away_prob',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='dnb_home_prob',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='dnb_prediction',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='ou_over_prob',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='ou_prediction',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='ou_under_prob',
        ),
    ]
