# Generated by Django 6.0.3 on 2026-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='odds_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='odds_d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='odds_h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='odds_over',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='odds_under',
            field=models.FloatField(default=0.0),
        ),
    ]
