# Generated by Django 6.0.3 on 2026-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_points_userbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
