# Generated by Django 6.0.3 on 2026-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_rank_userprofile_win_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('total_matches', models.IntegerField(default=0)),
                ('hda_accuracy', models.FloatField(default=0.0)),
                ('ou_accuracy', models.FloatField(default=0.0)),
                ('btts_accuracy', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('league_name', 'season')},
            },
        ),
    ]
