# Generated by Django 6.0.3 on 2026-04-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_leagueperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('points', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_diff', models.IntegerField(default=0)),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='api.league')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('league', 'season', 'team_name')},
            },
        ),
    ]
