# Generated by Django 6.0.3 on 2026-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
