# Generated by Django 6.0.3 on 2026-04-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('match_date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('away_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_matches', to='api.league')),
            ],
        ),
    ]
