# Generated by Django 6.0.3 on 2026-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_knockoutmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_score_extra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_score_half',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_score_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_score_regular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_score_extra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_score_half',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_score_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_score_regular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
